import Head from 'next/head';

import { useEffect, useLayoutEffect, useRef } from 'react';
import { HocuspocusProvider } from '@hocuspocus/provider';
import { EditorContent, useEditor } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Collaboration from '@tiptap/extension-collaboration';
import dynamic from 'next/dynamic';
const Tiptap = dynamic(() => import('../components/Tiptap'), {
	loading: () => <div>Loading</div>,
	ssr: false,
});

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='flex w-screen h-screen justify-center items-center'>
				<h1 className='font-bold text-md'>Mini Google Docs</h1>
				<button>Create Document</button>
			</main>
		</>
	);
}
